$(document).ready(function(){
  $(".hide").hide();
  $(".harmoni").click(function(){
    $(".hide").hide();
    $(".harmoni-planet").toggle();
  });
  $(".quorvex").click(function(){
    $(".hide").hide();
    $(".quorvex-sys").toggle();
  });
  $(".vern").click(function(){
    $(".hide").hide();
    $(".vern-sys").toggle();
  });
  $(".meili").click(function(){
    $(".hide").hide();
    $(".meili-sys").toggle();
  });
  $(".tera").click(function(){
    $(".hide").hide();
    $(".tera-sys").toggle();
  });
  $(".durnir").click(function(){
    $(".hide").hide();
    $(".durnir-sys").toggle();
  });
  $(".eaquen").click(function(){
    $(".hide").hide();
    $(".eaquen-sys").toggle();
  });
  $(".syl").click(function(){
    $(".hide").hide();
    $(".syl-sys").toggle();
  });
  $(".lirilion").click(function(){
    $(".hide").hide();
    $(".lirilion-sys").toggle();
  });
  $(".close").click(function(){
    $(".hide").hide();
  });
});